### ISSUE TITLE
invalid char? when running "go run main.go"

### ISSUE THREAD

**Issue by nolansingroy** [gmlewis/go-gerber#6]
Nolans-Air:dual-bifilar-coil nolansingroy$ ls
README.md			main.go
dual-bifilar-coil-diagram.png	view.sh
dual-bifilar-coil-layers.gif
Nolans-Air:dual-bifilar-coil nolansingroy$ go run main.go
go: extracting github.com/gmlewis/go-fonts v0.0.6
-> unzip /Users/nolansingroy/go/pkg/mod/cache/download/github.com/gmlewis/go-fonts/@v/v0.0.6.zip: malformed file path "fonts/airstream/Nick's Fonts License.txt": invalid char '\''
build command-line-arguments: cannot load github.com/gmlewis/go-fonts/fonts: unzip /Users/nolansingroy/go/pkg/mod/cache/download/github.com/gmlewis/go-fonts/@v/v0.0.6.zip: malformed file path "fonts/airstream/Nick's Fonts License.txt": invalid char '\''
Nolans-Air:dual-bifilar-coil nolansingroy$

**Comment by gmlewis** [comment]
Oh yes, I've seen this problem with the license file in one or two of the fonts.
I believe you can safely ignore the message.
If you do a `git clone` you will also see the message but you can ignore it.
I'm going to have no internet access starting now for the next week but hopefully you can work around the problem and I'll fix the license files when I get back.

**Comment by gmlewis** [comment]
Fixed by [v0.0.1](https://github.com/gmlewis/go-gerber/releases/tag/v0.0.1)
